# Generated by Django 4.2.4 on 2023-12-29 08:22

import BS_shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image1',
            field=models.ImageField(blank=True, null=True, upload_to=BS_shop.models.getFileName),
        ),
    ]
