# Generated by Django 4.2.4 on 2024-02-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BS_shop', '0004_cart_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
